export const FontSizes = {
  small: {
    tiny: 10,
    small: 12,
    body: 14,
    title: 16,
    heading: 18,
    large: 20,
  },
  medium: {
    tiny: 12,
    small: 14,
    body: 16,
    title: 18,
    heading: 20,
    large: 22,
  },
  large: {
    tiny: 14,
    small: 16,
    body: 18,
    title: 20,
    heading: 22,
    large: 24,
  },
  xlarge: {
    tiny: 16,
    small: 18,
    body: 20,
    title: 22,
    heading: 24,
    large: 26,
  },
};

export const FontFamilies = {
  default: {
    regular: 'System',
    medium: 'System',
    bold: 'System',
  },
  modern: {
    regular: 'SF Pro Text',
    medium: 'SF Pro Text Medium', 
    bold: 'SF Pro Text Bold',
  },
  classic: {
    regular: 'Times New Roman',
    medium: 'Times New Roman',
    bold: 'Times New Roman Bold',
  },
  playful: {
    regular: 'Comic Sans MS',
    medium: 'Comic Sans MS',
    bold: 'Comic Sans MS Bold',
  },
};

export const Themes = {
  light: {
    background: '#FFFFFF',
    surface: '#F5F5F5',
    surfaceVariant: '#EEEEEE',
    primary: '#8B5CF6',
    primaryDark: '#7C3AED',
    primaryLight: '#A78BFA',
    text: '#000000',
    textSecondary: '#666666',
    textMuted: '#999999',
    messageSent: '#8B5CF6',
    messageReceived: '#E5E5E5',
    success: '#10B981',
    error: '#EF4444',
    warning: '#F59E0B',
    border: '#DDDDDD',
    divider: '#EEEEEE',
    inputBackground: '#F9F9F9',
    inputBorder: '#DDDDDD',
    inputFocus: '#8B5CF6',
  },
  dark: {
    background: '#1A1A1A',
    surface: '#2D2D2D',
    surfaceVariant: '#3A3A3A',
    primary: '#8B5CF6',
    primaryDark: '#7C3AED',
    primaryLight: '#A78BFA',
    text: '#FFFFFF',
    textSecondary: '#CCCCCC',
    textMuted: '#888888',
    messageSent: '#8B5CF6',
    messageReceived: '#3D3D3D',
    success: '#10B981',
    error: '#EF4444',
    warning: '#F59E0B',
    border: '#555555',
    divider: '#444444',
    inputBackground: '#2A2A2A',
    inputBorder: '#555555',
    inputFocus: '#8B5CF6',
  },
  absolute_dark: {
    background: '#000000',
    surface: '#111111',
    surfaceVariant: '#1A1A1A',
    primary: '#8B5CF6',
    primaryDark: '#7C3AED',
    primaryLight: '#A78BFA',
    text: '#FFFFFF',
    textSecondary: '#B3B3B3',
    textMuted: '#666666',
    messageSent: '#8B5CF6',
    messageReceived: '#2D2D2D',
    success: '#10B981',
    error: '#EF4444',
    warning: '#F59E0B',
    border: '#333333',
    divider: '#222222',
    inputBackground: '#1A1A1A',
    inputBorder: '#333333',
    inputFocus: '#8B5CF6',
  },
};

export const ChatBubbleStyles = {
  default: {
    borderRadius: 20,
    paddingHorizontal: 16,
    paddingVertical: 10,
  },
  rounded: {
    borderRadius: 25,
    paddingHorizontal: 18,
    paddingVertical: 12,
  },
  square: {
    borderRadius: 8,
    paddingHorizontal: 14,
    paddingVertical: 10,
  },
  minimal: {
    borderRadius: 12,
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
};

export const DefaultWallpapers = [
  { id: 'none', name: 'Sem papel de parede', preview: null },
  { id: 'gradient1', name: 'Gradiente Roxo', preview: 'linear-gradient(135deg, #667eea 0%, #764ba2 100%)' },
  { id: 'gradient2', name: 'Gradiente Escuro', preview: 'linear-gradient(135deg, #232526 0%, #414345 100%)' },
  { id: 'pattern1', name: 'Padrão Geométrico', preview: 'https://images.unsplash.com/photo-1557683316-973673baf926?w=400' },
  { id: 'pattern2', name: 'Textura Escura', preview: 'https://images.unsplash.com/photo-1518173835740-f5d14111d76a?w=400' },
];