workflows:
  anvic-expo-android:
    name: Anvic Expo Android Build
    max_build_duration: 120
    environment:
      node: latest
    scripts:
      - name: Instalar dependências ignorando conflitos
        script: |
          npm install -g eas-cli
          npm install --legacy-peer-deps
      - name: Build Android com EAS
        script: |
          npx eas-cli build --platform android --non-interactive
    artifacts:
      - '**/*.apk'
    publishing:
      email:
        recipients:
          - victoralefefernandes@gmail.com
