workflows:
  react-native-android:
    name: React Native Android Build
    max_build_duration: 60
    environment:
      node: latest
      java: 17
      android: latest
    scripts:
      - name: Instalar dependências
        script: |
          npm install
      - name: Build APK
        script: |
          cd android
          ./gradlew assembleRelease
    artifacts:
      - android/app/build/outputs/**/*.apk
    publishing:
      email:
        recipients:
          - victoralefefernandes@outlook.com
