workflows:
  build-android-debug:
    name: Build Android Debug
    max_build_duration: 60
    instance_type: mac_mini_m2
    environment:
      node: 18
      npm: true
      groups:
        - google_play
    scripts:
      - name: Instalar dependências
        script: npm install
      - name: Build APK debug
        script: |
          cd android
          ./gradlew assembleDebug
    artifacts:
      - android/app/build/outputs/**/*.apk
