workflows:
  anvic-debug:
    name: Build Anvic Debug APK
    max_build_duration: 60
    environment:
      node: latest
      npm: latest
    scripts:
      - name: Instalar dependências
        script: |
          npm install --legacy-peer-deps
      - name: Build APK debug
        script: |
          cd android
          ./gradlew assembleDebug
    artifacts:
      - android/app/build/outputs/**/*.apk
