workflows:
  anvic-expo-android:
    name: Anvic Expo Android Build
    max_build_duration: 120
    environment:
      node: latest
    scripts:
      - name: Build Android com EAS
        script: |
          npm install -g eas-cli
          npx eas-cli build --platform android --non-interactive
    artifacts:
      - '**/*.apk'
    publishing:
      email:
        recipients:
          - victoralefefrnandes@gmail.com
