name: Build Android Debug APK for OnSpace App
on:
  push:
    branches:
      - main  # Ajuste para o branch correto (ex.: master)
  workflow_dispatch:  # Permite disparar manualmente
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'  # Compatível com projetos modernos

      - name: Cache node modules
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json', '**/package.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: |
          if [ -f package.json ]; then
            if [ -f package-lock.json ]; then
              npm ci
            else
              npm install
            fi
          else
            echo "No package.json found. Skipping dependency installation."
          fi

      - name: Check for build script
        run: |
          if [ -f build.gradle ]; then
            echo "Android native project detected."
            chmod +x gradlew
            ./gradlew assembleDebug
          elif [ -f package.json ] && grep -q "build" package.json; then
            echo "Running custom build script from package.json."
            npm run build
          else
            echo "No build script or gradle file found. Please configure build steps manually."
            exit 1
          fi
        continue-on-error: false

      - name: Upload APK or Build Artifact
        run: |
          if [ -f app/build/outputs/apk/debug/app-debug.apk ]; then
            echo "Uploading Android APK."
            mkdir -p artifacts
            cp app/build/outputs/apk/debug/app-debug.apk artifacts/
          elif [ -d dist ] || [ -d build ]; then
            echo "Uploading web build artifact."
            mkdir -p artifacts
            cp -r dist/* build/* artifacts/ || echo "No dist or build folder found."
          else
            echo "No APK or build artifact found. Check configuration."
            exit 1
          fi

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-build
          path: artifacts/
          retention-days: 30

      - name: Notify failure (optional)
        if: failure()
        run: echo "Build failed! Check the logs for details."
